import CoreGraphics
import Foundation
import ImageIO

public struct ImageMetadata: Equatable, Sendable {
    public let name: String
    public let path: String
    public let fileSize: Int64
    public let createdAt: Date?
    public let modifiedAt: Date?
    public let pixelSize: CGSize
    public let format: String
    public let colorSpace: String
    public let bitDepth: Int?
    public let dateTaken: Date?
    public let camera: String?
    public let lens: String?
    public let iso: Int?
    public let aperture: Double?
    public let shutterSpeed: Double?
    // Additional EXIF
    public let focalLength: Double?
    public let exposureCompensation: Double?
    public let flash: String?
    public let meteringMode: String?
    public let whiteBalance: String?
    public let exposureMode: String?
    public let subjectDistance: Double?
    public let digitalZoomRatio: Double?
    // IPTC
    public let caption: String?
    public let keywords: [String]
    public let copyright: String?
    public let credit: String?
    public let byline: String?
    public let city: String?
    public let country: String?
    public let headline: String?
    public let objectName: String?

    public let latitude: Double?
    public let longitude: Double?
    public let altitude: Double?

    public var formattedFileSize: String {
        ByteCountFormatter.string(fromByteCount: fileSize, countStyle: .file)
    }

    public var dimensionsText: String {
        "\(Int(pixelSize.width)) × \(Int(pixelSize.height))"
    }

    public var apertureText: String? {
        aperture.map { "ƒ/\(String(format: "%.1f", $0))" }
    }

    public var shutterText: String? {
        guard let s = shutterSpeed else { return nil }
        if s >= 1 {
            return "\(String(format: "%.0f", s))s"
        } else {
            let frac = Int((1 / s).rounded())
            return "1/\(frac)s"
        }
    }

    /// Formatted location string in DMS, e.g. "37°46'29\" N, 122°25'09\" W · 12 m".
    public var locationText: String? {
        guard let lat = latitude, let lon = longitude else { return nil }
        let latDir = lat >= 0 ? "N" : "S"
        let lonDir = lon >= 0 ? "E" : "W"

        func dms(_ decimal: Double) -> String {
            let absVal = abs(decimal)
            let d = Int(absVal)
            let m = Int((absVal - Double(d)) * 60)
            let s = (absVal - Double(d) - Double(m) / 60) * 3600
            return "\(d)°\(m)'\(String(format: "%.0f", s))\""
        }

        var result = "\(dms(lat)) \(latDir), \(dms(lon)) \(lonDir)"
        if let alt = altitude {
            let sign = alt >= 0 ? "" : "−"
            result += " · \(sign)\(String(format: "%.0f", abs(alt))) m"
        }
        return result
    }

    public var dateTakenText: String? {
        dateTaken.map { DateFormatter.localizedString(from: $0, dateStyle: .medium, timeStyle: .short) }
    }

    /// Human-readable plain-text representation for export.
    public var exportText: String {
        var lines: [String] = []
        let sep = "────────────────────────────────────────"

        lines.append("Readpic — Image Information")
        lines.append(sep)

        lines.append("")
        lines.append("▸ File")
        lines.append("  Name:       \(name)")
        lines.append("  Path:       \(path)")
        lines.append("  Size:       \(formattedFileSize)")
        if let c = createdAt { lines.append("  Created:    \(c.formatted())") }
        if let m = modifiedAt { lines.append("  Modified:   \(m.formatted())") }

        lines.append("")
        lines.append("▸ Image")
        lines.append("  Dimensions: \(dimensionsText)")
        lines.append("  Format:     \(format)")
        lines.append("  Color Space: \(colorSpace)")
        if let bd = bitDepth { lines.append("  Bit Depth:  \(bd)-bit") }

        if dateTaken != nil || camera != nil || lens != nil || iso != nil || aperture != nil || shutterSpeed != nil {
            lines.append("")
            lines.append("▸ Camera")
            if let d = dateTakenText { lines.append("  Date Taken: \(d)") }
            if let c = camera { lines.append("  Camera:     \(c)") }
            if let l = lens { lines.append("  Lens:       \(l)") }
            if let i = iso { lines.append("  ISO:        \(i)") }
            if let a = apertureText { lines.append("  Aperture:   \(a)") }
            if let s = shutterText { lines.append("  Shutter:    \(s)") }
        }

        if let loc = locationText {
            lines.append("")
            lines.append("▸ Location")
            lines.append("  \(loc)")
        }

        lines.append("")
        lines.append(sep)
        lines.append("Generated by Readpic")

        return lines.joined(separator: "\n")
    }
}

public struct MetadataReader: Sendable {
    public init() {}

    public func read(url: URL, pixelSize: CGSize) -> ImageMetadata {
        let resourceValues = try? url.resourceValues(forKeys: [.fileSizeKey, .creationDateKey, .contentModificationDateKey])

        let source = CGImageSourceCreateWithURL(url as CFURL, [kCGImageSourceShouldCache: false] as CFDictionary)
        let exif = readEXIF(source: source)
        let gps = readGPS(source: source)
        let iptc = readIPTC(source: source)

        let actualPixelSize: CGSize
        if pixelSize == .zero, let source,
           let props = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any] {
            let w = (props[kCGImagePropertyPixelWidth] as? CGFloat) ?? 0
            let h = (props[kCGImagePropertyPixelHeight] as? CGFloat) ?? 0
            actualPixelSize = CGSize(width: w, height: h)
        } else {
            actualPixelSize = pixelSize
        }

        return ImageMetadata(
            name: url.lastPathComponent,
            path: url.path,
            fileSize: Int64(resourceValues?.fileSize ?? 0),
            createdAt: resourceValues?.creationDate,
            modifiedAt: resourceValues?.contentModificationDate,
            pixelSize: actualPixelSize,
            format: url.pathExtension.uppercased(),
            colorSpace: colorSpaceName(source: source),
            bitDepth: readBitDepth(source: source),
            dateTaken: exif.dateTaken,
            camera: exif.camera,
            lens: exif.lens,
            iso: exif.iso,
            aperture: exif.aperture,
            shutterSpeed: exif.shutterSpeed,
            focalLength: exif.focalLength,
            exposureCompensation: exif.exposureCompensation,
            flash: exif.flash,
            meteringMode: exif.meteringMode,
            whiteBalance: exif.whiteBalance,
            exposureMode: exif.exposureMode,
            subjectDistance: exif.subjectDistance,
            digitalZoomRatio: exif.digitalZoomRatio,
            caption: iptc.caption,
            keywords: iptc.keywords,
            copyright: iptc.copyright,
            credit: iptc.credit,
            byline: iptc.byline,
            city: iptc.city,
            country: iptc.country,
            headline: iptc.headline,
            objectName: iptc.objectName,
            latitude: gps.latitude,
            longitude: gps.longitude,
            altitude: gps.altitude
        )
    }

    private func readFlash(_ flashValue: Int?) -> String? {
        guard let v = flashValue else { return nil }
        let fired = (v & 0x1) != 0
        let strobeReturn = (v >> 1) & 0x3
        let mode = (v >> 3) & 0x3
        let function = (v >> 5) & 0x1
        let redEye = (v >> 6) & 0x1

        var parts: [String] = []
        parts.append(fired ? "Fired" : "Did not fire")
        if fired {
            switch strobeReturn {
            case 0: break
            case 2: parts.append("Strobe return light not detected")
            case 3: parts.append("Strobe return light detected")
            default: break
            }
            switch mode {
            case 1: parts.append("Compulsory flash firing")
            case 2: parts.append("Compulsory flash suppression")
            case 3: parts.append("Auto mode")
            default: break
            }
        }
        if function == 1 { parts.append("Flash function present") }
        switch redEye {
        case 1: parts.append("No red-eye reduction")
        case 2: parts.append("Red-eye reduction")
        default: break
        }
        return parts.joined(separator: ", ")
    }

    private func readMeteringMode(_ v: Int?) -> String? {
        guard let v else { return nil }
        switch v {
        case 1: return "Average"
        case 2: return "Center-weighted average"
        case 3: return "Spot"
        case 4: return "Multi-spot"
        case 5: return "Multi-segment"
        case 6: return "Partial"
        case 255: return "Other"
        default: return nil
        }
    }

    private func readWhiteBalance(_ v: Int?) -> String? {
        guard let v else { return nil }
        switch v {
        case 0: return "Auto"
        case 1: return "Manual"
        case 2: return "Custom"
        default: return nil
        }
    }

    private func readExposureMode(_ v: Int?) -> String? {
        guard let v else { return nil }
        switch v {
        case 0: return "Auto"
        case 1: return "Manual"
        case 2: return "Auto bracket"
        default: return nil
        }
    }

    private func readEXIF(source: CGImageSource?) -> (dateTaken: Date?, camera: String?, lens: String?, iso: Int?, aperture: Double?, shutterSpeed: Double?, focalLength: Double?, exposureCompensation: Double?, flash: String?, meteringMode: String?, whiteBalance: String?, exposureMode: String?, subjectDistance: Double?, digitalZoomRatio: Double?) {
        guard let source,
              let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any] else {
            return (nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil)
        }

        let exifDict = properties[kCGImagePropertyExifDictionary] as? [CFString: Any]
        let tiffDict = properties[kCGImagePropertyTIFFDictionary] as? [CFString: Any]

        let dateTaken: Date?
        if let dateStr = exifDict?[kCGImagePropertyExifDateTimeOriginal] as? String {
            let formatter = DateFormatter()
            formatter.dateFormat = "yyyy:MM:dd HH:mm:ss"
            dateTaken = formatter.date(from: dateStr)
        } else {
            dateTaken = nil
        }

        let make = tiffDict?[kCGImagePropertyTIFFMake] as? String ?? ""
        let model = tiffDict?[kCGImagePropertyTIFFModel] as? String ?? ""
        let camera: String?
        if !make.isEmpty && !model.isEmpty {
            camera = "\(make) \(model)"
        } else if !model.isEmpty {
            camera = model
        } else if !make.isEmpty {
            camera = make
        } else {
            camera = nil
        }

        let lens = exifDict?[kCGImagePropertyExifLensModel] as? String

        let iso = (exifDict?[kCGImagePropertyExifISOSpeedRatings] as? [NSNumber])?.first?.intValue

        let aperture = (exifDict?[kCGImagePropertyExifFNumber] as? Double)

        let shutterSpeed: Double?
        if let exposureTime = exifDict?[kCGImagePropertyExifExposureTime] as? Double {
            shutterSpeed = exposureTime
        } else {
            shutterSpeed = nil
        }

        let focalLength = exifDict?[kCGImagePropertyExifFocalLength] as? Double
        let exposureCompensation = exifDict?[kCGImagePropertyExifExposureBiasValue] as? Double
        let flash = readFlash(exifDict?[kCGImagePropertyExifFlash] as? Int)
        let meteringMode = readMeteringMode(exifDict?[kCGImagePropertyExifMeteringMode] as? Int)
        let whiteBalance = readWhiteBalance(exifDict?[kCGImagePropertyExifWhiteBalance] as? Int)
        let exposureMode = readExposureMode(exifDict?[kCGImagePropertyExifExposureMode] as? Int)
        let subjectDistance = exifDict?[kCGImagePropertyExifSubjectDistance] as? Double
        let digitalZoomRatio = exifDict?[kCGImagePropertyExifDigitalZoomRatio] as? Double

        return (dateTaken, camera, lens, iso, aperture, shutterSpeed, focalLength, exposureCompensation, flash, meteringMode, whiteBalance, exposureMode, subjectDistance, digitalZoomRatio)
    }

    private func readIPTC(source: CGImageSource?) -> (caption: String?, keywords: [String], copyright: String?, credit: String?, byline: String?, city: String?, country: String?, headline: String?, objectName: String?) {
        guard let source,
              let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
              let iptcDict = properties[kCGImagePropertyIPTCDictionary] as? [CFString: Any]
        else { return (nil, [], nil, nil, nil, nil, nil, nil, nil) }

        let caption = iptcDict["Caption" as CFString] as? String
        let keywords = (iptcDict["Keywords" as CFString] as? [String]) ?? []
        let copyright = iptcDict["CopyrightNotice" as CFString] as? String
        let credit = iptcDict["Credit" as CFString] as? String
        let byline = iptcDict["Byline" as CFString] as? String
        let city = iptcDict["City" as CFString] as? String
        let country = iptcDict["CountryName" as CFString] as? String
        let headline = iptcDict["Headline" as CFString] as? String
        let objectName = iptcDict["ObjectName" as CFString] as? String

        return (caption, keywords, copyright, credit, byline, city, country, headline, objectName)
    }

    private func colorSpaceName(source: CGImageSource?) -> String {
        guard let source,
              let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any] else {
            return "Unknown"
        }

        if let profileName = properties[kCGImagePropertyProfileName] as? String {
            return profileName
        }

        if let colorModel = properties[kCGImagePropertyColorModel] as? String {
            return colorModel
        }

        return "Unknown"
    }

    private func readGPS(source: CGImageSource?) -> (latitude: Double?, longitude: Double?, altitude: Double?) {
        guard let source,
              let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
              let gpsDict = properties[kCGImagePropertyGPSDictionary] as? [CFString: Any]
        else { return (nil, nil, nil) }

        let rawLat = gpsDict[kCGImagePropertyGPSLatitude] as? Double
        let rawLon = gpsDict[kCGImagePropertyGPSLongitude] as? Double
        let latRef = gpsDict[kCGImagePropertyGPSLatitudeRef] as? String
        let lonRef = gpsDict[kCGImagePropertyGPSLongitudeRef] as? String

        let latitude: Double?
        if let lat = rawLat {
            latitude = latRef == "S" ? -lat : lat
        } else {
            latitude = nil
        }

        let longitude: Double?
        if let lon = rawLon {
            longitude = lonRef == "W" ? -lon : lon
        } else {
            longitude = nil
        }

        var altitude: Double?
        if let alt = gpsDict[kCGImagePropertyGPSAltitude] as? Double {
            let altRef = gpsDict[kCGImagePropertyGPSAltitudeRef] as? Int
            altitude = altRef == 1 ? -alt : alt
        }

        return (latitude, longitude, altitude)
    }

    private func readBitDepth(source: CGImageSource?) -> Int? {
        guard let source,
              let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any] else {
            return nil
        }
        return properties[kCGImagePropertyDepth] as? Int
    }
}
