import CoreGraphics
import Foundation
import ImageIO

public struct ImageMetadata: Equatable, Sendable {
    public let name: String
    public let path: String
    public let fileSize: Int64
    public let createdAt: Date?
    public let modifiedAt: Date?
    public let pixelSize: CGSize
    public let format: String
    public let colorSpace: String
    public let bitDepth: Int?
    public let dateTaken: Date?
    public let camera: String?
    public let lens: String?
    public let iso: Int?
    public let aperture: Double?
    public let shutterSpeed: Double?
    public let latitude: Double?
    public let longitude: Double?
    public let altitude: Double?

    public var formattedFileSize: String {
        ByteCountFormatter.string(fromByteCount: fileSize, countStyle: .file)
    }

    public var dimensionsText: String {
        "\(Int(pixelSize.width)) × \(Int(pixelSize.height))"
    }

    public var apertureText: String? {
        aperture.map { "ƒ/\(String(format: "%.1f", $0))" }
    }

    public var shutterText: String? {
        guard let s = shutterSpeed else { return nil }
        if s >= 1 {
            return "\(String(format: "%.0f", s))s"
        } else {
            let frac = Int((1 / s).rounded())
            return "1/\(frac)s"
        }
    }

    /// Formatted location string in DMS, e.g. "37°46'29\" N, 122°25'09\" W · 12 m".
    public var locationText: String? {
        guard let lat = latitude, let lon = longitude else { return nil }
        let latDir = lat >= 0 ? "N" : "S"
        let lonDir = lon >= 0 ? "E" : "W"

        func dms(_ decimal: Double) -> String {
            let absVal = abs(decimal)
            let d = Int(absVal)
            let m = Int((absVal - Double(d)) * 60)
            let s = (absVal - Double(d) - Double(m) / 60) * 3600
            return "\(d)°\(m)'\(String(format: "%.0f", s))\""
        }

        var result = "\(dms(lat)) \(latDir), \(dms(lon)) \(lonDir)"
        if let alt = altitude {
            let sign = alt >= 0 ? "" : "−"
            result += " · \(sign)\(String(format: "%.0f", abs(alt))) m"
        }
        return result
    }

    public var dateTakenText: String? {
        dateTaken.map { DateFormatter.localizedString(from: $0, dateStyle: .medium, timeStyle: .short) }
    }

    /// Human-readable plain-text representation for export.
    public var exportText: String {
        var lines: [String] = []
        let sep = "────────────────────────────────────────"

        lines.append("Readpic — Image Information")
        lines.append(sep)

        lines.append("")
        lines.append("▸ File")
        lines.append("  Name:       \(name)")
        lines.append("  Path:       \(path)")
        lines.append("  Size:       \(formattedFileSize)")
        if let c = createdAt { lines.append("  Created:    \(c.formatted())") }
        if let m = modifiedAt { lines.append("  Modified:   \(m.formatted())") }

        lines.append("")
        lines.append("▸ Image")
        lines.append("  Dimensions: \(dimensionsText)")
        lines.append("  Format:     \(format)")
        lines.append("  Color Space: \(colorSpace)")
        if let bd = bitDepth { lines.append("  Bit Depth:  \(bd)-bit") }

        if dateTaken != nil || camera != nil || lens != nil || iso != nil || aperture != nil || shutterSpeed != nil {
            lines.append("")
            lines.append("▸ Camera")
            if let d = dateTakenText { lines.append("  Date Taken: \(d)") }
            if let c = camera { lines.append("  Camera:     \(c)") }
            if let l = lens { lines.append("  Lens:       \(l)") }
            if let i = iso { lines.append("  ISO:        \(i)") }
            if let a = apertureText { lines.append("  Aperture:   \(a)") }
            if let s = shutterText { lines.append("  Shutter:    \(s)") }
        }

        if let loc = locationText {
            lines.append("")
            lines.append("▸ Location")
            lines.append("  \(loc)")
        }

        lines.append("")
        lines.append(sep)
        lines.append("Generated by Readpic")

        return lines.joined(separator: "\n")
    }
}

public struct MetadataReader: Sendable {
    public init() {}

    public func read(url: URL, pixelSize: CGSize) -> ImageMetadata {
        let resourceValues = try? url.resourceValues(forKeys: [.fileSizeKey, .creationDateKey, .contentModificationDateKey])

        let source = CGImageSourceCreateWithURL(url as CFURL, [kCGImageSourceShouldCache: false] as CFDictionary)
        let exif = readEXIF(source: source)
        let gps = readGPS(source: source)

        let actualPixelSize: CGSize
        if pixelSize == .zero, let source,
           let props = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any] {
            let w = (props[kCGImagePropertyPixelWidth] as? CGFloat) ?? 0
            let h = (props[kCGImagePropertyPixelHeight] as? CGFloat) ?? 0
            actualPixelSize = CGSize(width: w, height: h)
        } else {
            actualPixelSize = pixelSize
        }

        return ImageMetadata(
            name: url.lastPathComponent,
            path: url.path,
            fileSize: Int64(resourceValues?.fileSize ?? 0),
            createdAt: resourceValues?.creationDate,
            modifiedAt: resourceValues?.contentModificationDate,
            pixelSize: actualPixelSize,
            format: url.pathExtension.uppercased(),
            colorSpace: colorSpaceName(source: source),
            bitDepth: readBitDepth(source: source),
            dateTaken: exif.dateTaken,
            camera: exif.camera,
            lens: exif.lens,
            iso: exif.iso,
            aperture: exif.aperture,
            shutterSpeed: exif.shutterSpeed,
            latitude: gps.latitude,
            longitude: gps.longitude,
            altitude: gps.altitude
        )
    }

    private func readEXIF(source: CGImageSource?) -> (dateTaken: Date?, camera: String?, lens: String?, iso: Int?, aperture: Double?, shutterSpeed: Double?) {
        guard let source,
              let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any] else {
            return (nil, nil, nil, nil, nil, nil)
        }

        let exifDict = properties[kCGImagePropertyExifDictionary] as? [CFString: Any]
        let tiffDict = properties[kCGImagePropertyTIFFDictionary] as? [CFString: Any]

        let dateTaken: Date?
        if let dateStr = exifDict?[kCGImagePropertyExifDateTimeOriginal] as? String {
            let formatter = DateFormatter()
            formatter.dateFormat = "yyyy:MM:dd HH:mm:ss"
            dateTaken = formatter.date(from: dateStr)
        } else {
            dateTaken = nil
        }

        let make = tiffDict?[kCGImagePropertyTIFFMake] as? String ?? ""
        let model = tiffDict?[kCGImagePropertyTIFFModel] as? String ?? ""
        let camera: String?
        if !make.isEmpty && !model.isEmpty {
            camera = "\(make) \(model)"
        } else if !model.isEmpty {
            camera = model
        } else if !make.isEmpty {
            camera = make
        } else {
            camera = nil
        }

        let lens = exifDict?[kCGImagePropertyExifLensModel] as? String

        let iso = (exifDict?[kCGImagePropertyExifISOSpeedRatings] as? [NSNumber])?.first?.intValue

        let aperture = (exifDict?[kCGImagePropertyExifFNumber] as? Double)

        let shutterSpeed: Double?
        if let exposureTime = exifDict?[kCGImagePropertyExifExposureTime] as? Double {
            shutterSpeed = exposureTime
        } else {
            shutterSpeed = nil
        }

        return (dateTaken, camera, lens, iso, aperture, shutterSpeed)
    }

    private func colorSpaceName(source: CGImageSource?) -> String {
        guard let source,
              let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any] else {
            return "Unknown"
        }

        if let profileName = properties[kCGImagePropertyProfileName] as? String {
            return profileName
        }

        if let colorModel = properties[kCGImagePropertyColorModel] as? String {
            return colorModel
        }

        return "Unknown"
    }

    private func readGPS(source: CGImageSource?) -> (latitude: Double?, longitude: Double?, altitude: Double?) {
        guard let source,
              let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
              let gpsDict = properties[kCGImagePropertyGPSDictionary] as? [CFString: Any]
        else { return (nil, nil, nil) }

        let rawLat = gpsDict[kCGImagePropertyGPSLatitude] as? Double
        let rawLon = gpsDict[kCGImagePropertyGPSLongitude] as? Double
        let latRef = gpsDict[kCGImagePropertyGPSLatitudeRef] as? String
        let lonRef = gpsDict[kCGImagePropertyGPSLongitudeRef] as? String

        let latitude: Double?
        if let lat = rawLat {
            latitude = latRef == "S" ? -lat : lat
        } else {
            latitude = nil
        }

        let longitude: Double?
        if let lon = rawLon {
            longitude = lonRef == "W" ? -lon : lon
        } else {
            longitude = nil
        }

        var altitude: Double?
        if let alt = gpsDict[kCGImagePropertyGPSAltitude] as? Double {
            let altRef = gpsDict[kCGImagePropertyGPSAltitudeRef] as? Int
            altitude = altRef == 1 ? -alt : alt
        }

        return (latitude, longitude, altitude)
    }

    private func readBitDepth(source: CGImageSource?) -> Int? {
        guard let source,
              let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any] else {
            return nil
        }
        return properties[kCGImagePropertyDepth] as? Int
    }
}
